### ISSUE TITLE
Handle Errors in CreateTopic response

### ISSUE THREAD

**Issue by pecigonzalo** [segmentio/topicctl#101]
Hi! I was leveraging your CLI as a library in a MVP project of mine, as it wraps nicely the `kafka-go` details I need to use. In doing so I found that `BrokerAdminClient.CreateTopic()` https://github.com/segmentio/topicctl/blob/master/pkg/admin/brokerclient.go#L452-L468 does not handle response errors.

The code
```go
func (c *BrokerAdminClient) CreateTopic(
	ctx context.Context,
	config kafka.TopicConfig,
) error {
	if c.config.ReadOnly {
		return errors.New("Cannot create topic in read-only mode")
	}

	req := kafka.CreateTopicsRequest{
		Topics: []kafka.TopicConfig{config},
	}
	log.Debugf("CreateTopics request: %+v", req)

	resp, err := c.client.CreateTopics(ctx, &req)
	log.Debugf("CreateTopics response: %+v (%+v)", resp, err)
	return err
}
```

The `resp` from `c.client.CreateTopics` contains an `Errors` field that could contain errors such as invalid parameters.

I don't know if this was intentionally unhandled, but I think we should either handle or return the `resp` along the error.

Depending on your answer, I'm happy to submit a PR to address it.

**Comment by hhahn-tw** [comment]
Hello - thanks for raising this issue. It's my understanding that this wasn't an intentional omission and would benefit from fleshing out further. A PR would be appreciated!

**Comment by pecigonzalo** [comment]
Perfect, ill prepare one

**Comment by pecigonzalo** [comment]
@hhahn-tw added a draft in https://github.com/segmentio/topicctl/pull/103
