### ISSUE TITLE
Make it work without zookeeper?

### ISSUE THREAD

**Issue by strigona-worksight** [segmentio/topicctl#13]
With [KIP-500](https://cwiki.apache.org/confluence/display/KAFKA/KIP-500%3A+Replace+ZooKeeper+with+a+Self-Managed+Metadata+Quorum) zookeeper will be removed, are there any plans to make this work without zookeeper? Additionally, I'm guessing this won't work with platforms like [Confluent Cloud](https://www.confluent.io/confluent-cloud) as zookeeper is not exposed - just the brokers.

**Comment by yolken-segment** [comment]
Yes, removing the need for ZK access in newer cluster versions is definitely in the medium-term roadmap. I'm just waiting on some changes to land in https://github.com/segmentio/kafka-go, then we'll need to refactor https://github.com/segmentio/topicctl/blob/master/pkg/admin/client.go to (optionally) support using broker APIs instead of ZK for each piece of functionality.

**Comment by strigona-worksight** [comment]
That sounds great! I look forward to using this tool.

**Comment by opsj** [comment]
In addition to removal of the zookeeper dependency, it would be great to have a support for clusters configured with SSL authentication.

**Comment by yolken-segment** [comment]
We are planning on addressing these things over the next few weeks! Details here: https://github.com/segmentio/topicctl/wiki/v1-Plan.

**Comment by yolken-segment** [comment]
Have the initial set of changes here: https://github.com/segmentio/topicctl/pull/32. Feel free to give that version a try, although it's still a WIP that hasn't been fully tested in production.

**Comment by yolken-segment** [comment]
Added TLS and SASL support into https://github.com/segmentio/topicctl/pull/32, and read-only operations seem to work against Confluent Cloud. Topic creation is not working for whatever reason (need to dig into that more), but feel free to give the other functionality a try...

**Comment by yolken-segment** [comment]
This has been fixed by https://github.com/segmentio/topicctl/pull/32!
