### ISSUE TITLE
Publish Docker image to Docker Hub?

### ISSUE THREAD

**Issue by DarrenTsung** [segmentio/topicctl#14]
Thanks for the awesome looking tool! I see in the circleci config that there's already an existing pipeline for pushing the image to AWS ECR, is it planned to push to a Docker Hub repository as well?

**Comment by sycured** [comment]
Can you prefer Quay.io instead of Docker Hub due to Docker Inc's change: https://twitter.com/kantrn/status/1298069674148548608?s=19

**Comment by yolken-segment** [comment]
I'm working on getting this set up. Please stay tuned!

**Comment by yolken-segment** [comment]
We now have a public docker image: `docker pull segment/topicctl`. I've also added this into the installation section of the README.
