### ISSUE TITLE
Will versions `1.12.0`, `1.13.0`, `1.14.0` and newer be available at DockerHub?

### ISSUE THREAD

**Issue by ricardo-overhaul** [segmentio/topicctl#179]
I see the latest version available at https://hub.docker.com/r/segment/topicctl/tags is `1.11.0`, will new versions become available soon?

**Comment by hhahn-tw** [comment]
Hello - thank you for bringing this to our attention. There was an issue with the CI setup that led it to skipping the push to Docker Hub that's now been corrected. A new release v1.14.1 has been pushed (unchanged from v1.14.0) and is present on Docker Hub now.
