### ISSUE TITLE
disable loading bar

### ISSUE THREAD

**Issue by abuckenheimer** [segmentio/topicctl#25]
Hey folks,

Awesome tool, this is something I've sorely needed. I wanted to incorporate this tool into some light bash scripting but I run into issues where the loading bar dirties the input I'm piping as stdin to other programs. Is there anyway to disable the loading bar?

For example I'm thinking of using [skim](https://github.com/lotabout/skim) to quickly jump around between topic offsets using fuzzy match. Can do so easily with something like:

```
topicctl --cluster-config cluster.yml get topics 2>&1 | sk --header-lines=4 -m --preview "topicctl get offsets {2} --cluster-config cluster.yml"
```
But the loading bar leaves weird artifacts in the first panel and then breaks the second panel (I see the loading bar flash and the screen go blank). Obviously this is just a nice to have, can do everything I need within your tool but some easy bash scripting expands the universe even further.

Thanks in advance!

**Comment by yolken-segment** [comment]
Thanks for the suggestion, can definitely add an option to disable those loading bars.

**Comment by yolken-segment** [comment]
Fixed in https://github.com/segmentio/topicctl/pull/27.

**Comment by abuckenheimer** [comment]
can confirm this works now! for reference heres an example of how I'm using:

```
get_topic() {
    topicctl --cluster-config ${1:-cluster.yml} get topics --no-spinner 2>&1 \
      | sk --header-lines=5 --preview "topicctl get offsets {2} --cluster-config ${1:-cluster.yml} --no-spinner 2>&1" \
      | awk '{print $1}'
}

get_topic ./path/to/config.yml
```
![image](https://user-images.githubusercontent.com/4197256/94503069-97b6d100-01d3-11eb-8ce3-f7b1eb7e2e20.png)
