### ISSUE TITLE
What are advantages to terraform-provider-kafka

### ISSUE THREAD

**Issue by Meemaw** [segmentio/topicctl#35]
Curious to understand advantages to: https://github.com/Mongey/terraform-provider-kafka for the `apply` part.

**Comment by yolken-segment** [comment]
I'm not personally familiar with that provider, but based on the docs I think the main distinguishing feature of `topicctl apply` is the ability to support more complex partition layouts (e.g., `in-rack`) and also the ability to manage data migrations if you're switching from one layout to another. If you're ok with the default layout and already use terraform, sticking with that tool might be easiest.

Also, it looks like that provider supports ssl, sasl, and acls out of the box. These are not ready yet in `topicctl`, although we're [actively working on them](https://github.com/segmentio/topicctl/wiki/v1-Plan#current-status-updated-nov-25-2020). :-)

Hope this helps.
