### ISSUE TITLE
AWS IAM Auth support

### ISSUE THREAD

**Issue by siagroove** [segmentio/topicctl#48]
Hi, 
I wanted to know if there are any plans to support AWS MSK IAM auth in future. In order to support that auth mechanism, their library needs to be imported: https://github.com/aws/aws-msk-iam-auth
But that library is supported in Java only, so that needs to be supported in golang as well. We are using MSK to deploy our kafka cluster with IAM auth, so currently we can't use Topicctl unless the aws iam auth support is added.

**Comment by yolken-segment** [comment]
It looks like we can do this once https://github.com/segmentio/kafka-go/issues/661 is fixed. Not sure on the timeframe there, but will check with the team to see how that task is being prioritized.

**Comment by siagroove** [comment]
That's great news! Thank you.

**Comment by yolken-segment** [comment]
kafka-go change is in progress: https://github.com/segmentio/kafka-go/pull/763

**Comment by yolken-segment** [comment]
Fixed in https://github.com/segmentio/topicctl/pull/57.
