### ISSUE TITLE
Problems trying to run "topicctl apply" with SASL authentication in AWS MSK

### ISSUE THREAD

**Issue by cigol1** [segmentio/topicctl#50]
I am working with an AWS MSK cluster with tls and sasl authentication.  When I try to run the **"topicctl apply**" with the bootstrap servers configured I have the following error:

`[2021-11-03 05:34:49] ERROR Admin client does not support features needed for apply; please use zk-based client instead.
`

When I configure the Zookeeper addresses I need to remove the _tls_ and _sasl_ config.  This gets me to a point where it can't connect to the broker with the following error:

`[2021-11-03 05:41:01] ERROR kafka.(*Client).CreateTopics: [8] Broker Not Available: not a client facing error and is used mostly by tools when a broker is not alive
`

I imagine it is unable to connect because of the lack of the authentication credentials.  Any thoughts on how I could get this to work in this environement?

**Comment by yolken-segment** [comment]
What version of Kafka are you running in MSK?

**Comment by yolken-segment** [comment]
Ahh, ok, that explains it- versions older than 2.4 can't use the broker-only mode for applies (sorry, should make that more clear in the docs). Most of the non-apply, read-only functionality should work, however (e.g. `get topics`, `get brokers`, etc.). 

You can use the mixed zookeeper/broker mode for applies in older versions of Kafka, but this doesn't work with authentication at the moment. Sorry about this.

**Comment by cigol1** [comment]
I see, thanks for the information.  Looks like AWS supports newer versions, I will look into running a newer version of Kafka.
