### ISSUE TITLE
Unable to parse the '$' character in saslPassword

### ISSUE THREAD

**Issue by cigol1** [segmentio/topicctl#53]
I have ran into an issue if that password contains a '$' it is removed, or it seems that it tries to perform variable expansion and since the variable is not present it replaces it with an empty string.  I have tried escaping and the double '$$', but it is always being replaced.

Any ideas on how to support?

The only "clever" way that I have seen that works is to actually create a variable that represent the '$' (ds=$) and modify the password to substitute all '$' chars with '${ds}' and let the substitution replace it.

**Comment by yolken-segment** [comment]
Sorry about that- I think this is due to https://github.com/segmentio/topicctl/pull/46. Let's see if we can come up with a way to disable that or escape the `$`s more easily.

**Comment by yolken-segment** [comment]
Urg, looks like there's no way to escape: https://github.com/golang/go/issues/43482. I think we should just add a flag to disable the environment replacement if desired.

**Comment by cigol1** [comment]
It took me a bit of time to figure this out.  I think it would be more desirable/intuitive that the environment replacement be disabled by default.  If a user wants to enable it, then it might be easier to figure out what is causing the issue.  At the end of the day, having a flag would be beneficial.  The solution I have is very hacky.

**Comment by yolken-segment** [comment]
This behavior has been fixed in https://github.com/segmentio/topicctl/pull/55; now, you need to opt-in to the environment replacement via the `--expand-env`, and it's not enabled by default.

Thanks for the report!
