### ISSUE TITLE
spec.sasl.mechanism from YAML is ignored if TOPICCTL_SASL_USERNAME or TOPICCTL_SASL_PASSWORD is set

### ISSUE THREAD

**Issue by JackKelly-Bellroy** [segmentio/topicctl#54]
We are using `topicctl` with environment variables to avoid hardcoding them in a `cluster.yaml` file. This causes `topicctl` to ignore the `sasl.mechanism` field in the yaml file.

It would be nice to be able to read credentials from the environment while also reading the mechanism from the config file. An in-between fix would be to listen to an environment variable for SASL mechanism also.

This applies to the `topicctl get topics` command, but doesn't seem to cause problems for `topicctl apply`.

**Comment by yolken-segment** [comment]
Hmm, I'm not able to reproduce this. Can you attach a sanitized version of your cluster config?

**Comment by yolken-segment** [comment]
This has been fixed in https://github.com/segmentio/topicctl/pull/55. Thanks for the report!

**Comment by JackKelly-Bellroy** [comment]
Confirmed working. Thanks for the fast turnaround!
