### ISSUE TITLE
CVE in go modules!

### ISSUE THREAD

**Issue by noorul** [segmentio/topicctl#65]
We are using Trivy (https://github.com/aquasecurity/trivy) tool for scanning vulnerabilities. In the Trivy report, we see the following 

<img width="1904" alt="Screenshot 2022-05-16 at 2 21 31 PM" src="https://user-images.githubusercontent.com/155376/168555523-eff561d9-9f05-4252-9456-19fa778b664e.png">

Can we upgrade these two modules to the latest version available?

**Comment by nikhleshgoenka** [comment]
**Thanks @noorul for tracking this**

**Comment by nikhleshgoenka** [comment]
Can the golang version be updated to latest stable also https://github.com/segmentio/topicctl/blob/75aefabd4f0a829bb0af9b7178b9052219178161/Dockerfile#L1

**Comment by yolken** [comment]
Thanks for the report, should be fixed in https://github.com/segmentio/topicctl/pull/66.

**Comment by noorul** [comment]
Thanks @yolken

**Comment by nikhleshgoenka** [comment]
Thanks @yolken  :)
