### ISSUE TITLE
Is there an arm arch image?

### ISSUE THREAD

**Issue by noorul** [segmentio/topicctl#73]

**Comment by yolken** [comment]
We don't have one at the moment, but I can look into adding it.

**Comment by vishnu-anil** [comment]
@noorul  you can build one using docker buildx. I used their Dockerfile and it works in arm based instances.

**Comment by yolken** [comment]
This should be fixed now. Please reopen if the latest image doesn't work for arm.

**Comment by noorul** [comment]
@yolken when could be the next release?

**Comment by yolken** [comment]
I released an hour or so ago?

**Comment by noorul** [comment]
Oh yes, my bad! I overlooked
